### ISSUE TITLE
new release - supports netinfo 5.x

### ISSUE THREAD

**Issue by alexisbronchart** [morrys/react-relay-offline#38] opened 2020-02-19 14:01 UTC
I tried to setup my relay environment **in a react-native app** by importing `Environment`, `Store` & `RecordSource` from `react-relay-offline` (no particular options). Now when I import `QueryRenderer` from `react-relay-offline`, I'm getting this error: `Cannot read property 'fetch' of undefined`

Seems to happen in OfflineFirst.js at this line :
`this.promisesRestore = Promise.all([netinfo_1.NetInfo.isConnected.fetch(), this.offlineStore.restore()])`

As far as I understand, the web implementation of [NetInfo](https://github.com/morrys/wora/blob/master/packages/netinfo/src/NetInfo.ts) has a fetch function on isConnected but the [native NetInfo](https://github.com/react-native-community/react-native-netinfo#api) doesn't have the same interface (anymore?).

**Comment by morrys** [comment] 2020-02-19 14:17
Which version of the netinfo library are you using?
Version 5 of the netinfo library is not currently supported:
https://github.com/morrys/wora/issues/32

This is because I am following the issue (recently resolved) https://github.com/react-native-community/react-native-netinfo/issues/174 regarding web support.

Their solution does not seem to me the most suitable for the web as a dependency with react-native-web is required.
Soon I will open an issue in the netinfo repository to highlight this problem.

**Comment by alexisbronchart** [comment] 2020-02-20 09:11
Yeah indeed I was running with Netinfo 5.5.0. I downgraded to 4.7.0.
About the web support I don't think they would enable it in another way than by using react-native-web since it's a react-native lib at its core. Might be best to keep using & updating @wora/netinfo ?

**Comment by morrys** [comment] 2020-02-20 11:55
Currently my policy is to try to contribute and integrate the functionality into existing and supported libraries.
Both with regards to Relay, Apollo and other dependencies.

If these proposals are rejected or ignored then I will implement these needs in my libraries :)

At the moment both relay and netinfo have not introduced important features that need the upgrade, so I'm giving them more time to evaluate my proposals :)

**Comment by alexisbronchart** [comment] 2020-04-07 10:09
@morrys are you planning to add this in v2? Latest netinfo has macOS support which I'm currently looking at 😇

**Comment by morrys** [comment] 2020-04-07 10:32
@alexisbronchart with version 2.0.0 I preferred to focus on v9 relay support and improve the codebase.

The next step will be to modify the wora / netinfo library to ensure v5 support and release it with a 2.x.0 version.

Suggestions or PR are welcome :)

**Comment by morrys** [comment] 2020-04-18 19:29
hi @alexisbronchart,
with the release 2.1.0 just released I have integrated support for netinfo v5.

I'd like to have your feedback before closing the issue.
thanks

**Comment by alexisbronchart** [comment] 2020-04-18 19:35
Amazing! I’ll try the update ASAP!

**Comment by alexisbronchart** [comment] 2020-04-20 15:30
I upgraded right away from 1.1.0 as long as relay 9.0.0 and I'm having a crash `RelayObservable undefined is not an object "operation.root"`. However installing my app on a device/simulator without any previously persisted store is working fine (aka newly installed build OR upgrade my a build of my app _before_ it was using react-relay-offline). Not sure where this is coming from.

**Comment by morrys** [comment] 2020-04-20 16:02
The error you detect may be caused by persistent data that is no longer compatible with relay v9.
Can you give me more information about the error?

There is certainly a workaround using the mergeState option of the persistence of the store https://morrys.github.io/wora/docs/cache-persist.html#cache-options

**Comment by morrys** [comment] 2020-04-20 16:08
Did you re-launch compilation with all relay libraries to version v9?

**Comment by morrys** [comment] 2020-04-20 17:18
@alexisbronchart, I just ran tests using the same sample project with different relay versions and I didn't find any problems.
Could you have accidentally had two different relay versions?
I will wait for your more details

thanks

**Comment by alexisbronchart** [comment] 2020-04-22 15:48
I don't really have more info than this.
<img width="704" alt="Screenshot 2020-04-22 at 17 37 26" src="https://user-images.githubusercontent.com/1279527/80002731-4be35b80-84c0-11ea-907b-859553fa4566.png">
I'm also rather sure that it is incompatible persistent data as you suggested since I also update relay to 9.0.0. Unless a store migration mechanism exists I guess I'll just purge the relay store on app update next time there's an incompatible relay update.

**Comment by morrys** [comment] 2020-04-23 10:48
@alexisbronchart, this detail is sufficient. The problem is caused by persisted data that is no longer compatible with relay v9.
Cleaning the store is an excellent solution.

I hope relay stops creating break changes on operations management :)

**Closed** 2020-04-23 10:49 UTC
Labels: enhancement
