### ISSUE TITLE
Support of Expo

### ISSUE THREAD

**Issue by Emetrop** [morrys/react-relay-offline#42] opened 2020-04-17 03:23 UTC
Hi,
I tried to use your library as an [expo](https://expo.io) react-native project and I have no luck to make it work.

You can check this minimal failing repo - https://github.com/Emetrop/relay-offline-test 

This is dump from console

```
Error: Unable to resolve module `./debugger-ui/debuggerWorker.d9da4ed7` from ``: 

None of these files exist:
  * debugger-ui/debuggerWorker.d9da4ed7(.native|.native.expo.ts|.expo.ts|.native.expo.tsx|.expo.tsx|.native.expo.js|.expo.js|.native.expo.jsx|.expo.jsx|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.wasm|.wasm)
  * debugger-ui/debuggerWorker.d9da4ed7/index(.native|.native.expo.ts|.expo.ts|.native.expo.tsx|.expo.tsx|.native.expo.js|.expo.js|.native.expo.jsx|.expo.jsx|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.wasm|.wasm)
    at ModuleResolver.resolveDependency (/Users/martin/Work/personal/relay-offline-test/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/martin/Work/personal/relay-offline-test/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/martin/Work/personal/relay-offline-test/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at /Users/martin/Work/personal/relay-offline-test/node_modules/metro/src/lib/transformHelpers.js:267:42
    at /Users/martin/Work/personal/relay-offline-test/node_modules/metro/src/Server.js:1305:37
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/martin/Work/personal/relay-offline-test/node_modules/metro/src/Server.js:99:24)
    at _next (/Users/martin/Work/personal/relay-offline-test/node_modules/metro/src/Server.js:119:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
and screenshot from app
![image](https://user-images.githubusercontent.com/7429956/79528604-cf282b80-8040-11ea-93d8-5c58f0993e5b.png)

so probably it's an issue with not supported `AsyncStorage` by expo which is explained here right?

https://github.com/react-native-community/async-storage/issues/72

So it means you can't do anything with that and we need to wait for adding support for `AsyncStorage` by expo?

**Comment by Emetrop** [comment] 2020-04-17 04:42
I tried to replace this import 

https://github.com/morrys/wora/blob/10bc18c9e42e06a13c9a3f18156c8315ba43307d/packages/cache-persist/src/createStorage.native.ts#L2

by this

`import { AsyncStorage } from 'react-native';`

and seems it fixed this problem but it brings another error 

`Cannot read property 'fetch' of undefined`
`- node_modules/@wora/offline-first/lib/OfflineFirst.js:48:35 in prototype.hydrate`

which is reference to this line https://github.com/morrys/wora/blob/10bc18c9e42e06a13c9a3f18156c8315ba43307d/packages/offline-first/src/OfflineFirst.ts#L91

**Comment by Emetrop** [comment] 2020-04-17 04:57
I created PR for that`NetInfo.fetch()` here

https://github.com/morrys/wora/pull/51

**Comment by morrys** [comment] 2020-04-17 07:51
hi @Emetrop,
The problem is caused by version 5 of netinfo and I had already planned to implement its support https://github.com/morrys/react-relay-offline/issues/38

I will look at your example project using expo and the PR you have done and I will give you some feedback :)

**Comment by morrys** [comment] 2020-04-18 19:27
hi @Emetrop,
with the release 2.1.0 https://github.com/morrys/react-relay-offline/releases/tag/v2.1.0 just released I have solved the compatibility problems with expo.
Netinfo v5 is now supported and native AsyncStorage is automatically used.

However, you must add the dependency of @react-native-community/async-storage.

I'd like to have your feedback before closing the issue.
Thank you

**Closed** 2020-05-02 12:40 UTC
